# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - ./database-data:/docker-entrypoint-initdb.d/
      # persist data even if container shuts down
    ports:
      - 5432:5432
volumes:
  data-db: # named volumes can be managed easier using docker-compose